version: '3'
services:
  thelounge:
    image: thelounge/thelounge:3.0.0-pre.6
    volumes:
      - thelounge:/var/opt/thelounge
      - ./config.js:/var/opt/thelounge/config.js
    ports:
      - "9000:9000"
  znc:
    image: znc:slim
    volumes:
      - znc:/znc-data
    ports:
      - "6697:6697"
      - "8080:8080"
volumes:
  thelounge:
  znc:
